# Generated by Django 4.2.7 on 2023-11-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimestampedModelMixin',
        ),
    ]
