version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB : secure_pass_db_dev
      POSTGRES_USER: amol_gode
      POSTGRES_PASSWORD: skp_db@123
    ports:
      - "5432:5432"



  backend:
    build: 
      context: ./backend_django/securePassKeeper
      dockerfile: Dockerfile 
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "securePassKeeper.wsgi:application"]
    volumes:
      - ./backend_django/securePassKeeper:/backend 
    ports:
      - "8000:8000"
    depends_on:
      - db
  

  frontend:
    build:
      context: ./frontend_react/secure-pass-keeper
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000
    volumes:
      - ./frontend_react/secure-pass-keeper/src:/frontend/src  
      - ./frontend_react/secure-pass-keeper/public:/frontend/public  
      - ./frontend_react/secure-pass-keeper/node_modules:/frontend/node_modules


    depends_on:
      - backend