version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB : secure_pass_db_dev
      POSTGRES_USER: amol_gode
      POSTGRES_PASSWORD: skp_db@123
    ports:
      - "5432:5432"



  web:
    build: 
      context: .
      dockerfile: Dockerfile 
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "securePassKeeper.wsgi:application"]
    volumes:
      - .:/backend 
    ports:
      - "8000:8000"
    depends_on:
      - db