# Generated by Django 4.2.7 on 2023-11-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_utils', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
    ]
