# Generated by Django 4.2.7 on 2023-11-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_extendeduser_created_at_extendeduser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='updated_at',
        ),
    ]
