# Generated by Django 4.2.7 on 2023-11-24 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_extendeduser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
