# Generated by Django 4.2.7 on 2023-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_extendeduser_created_at_extendeduser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user_salt_key',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='user_salt_byte',
            field=models.BinaryField(default=b'\xadZ\x85\x88\\\xbe\x83\xaf\xd1j\x8e\xf7DP \x84'),
            preserve_default=False,
        ),
    ]
