# Generated by Django 4.2.7 on 2023-11-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_extendeduser_user_salt_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='user_salt_byte',
            new_name='user_salt_bytecode',
        ),
    ]
