# Generated by Django 4.2.7 on 2023-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_user_salt_byte_extendeduser_user_salt_bytecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
